#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME="ask_yes_no_question"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#REPLACE_THIS_WITH_HEADER_INFO
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
printf_help() { printf "%b" "$(tput setaf "${2:-4}" 2>/dev/null)" "\t\t$1" "$(tput sgr0 2>/dev/null)";printf '\n'; }
get_desc() {
  local PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/usr/sbin"
  local appname="$(type -P "${PROG:-$APPNAME}" 2>/dev/null || command -v "${PROG:-$APPNAME}" 2>/dev/null)"
  local desc="$(grep ^"# @Description" "$appname" 2>/dev/null | grep ' : ' | sed 's#..* : ##g' | grep '^')"
  [ -n "$desc" ] && printf '%s\n' "$desc" || return 1
}
printf_descr() { [ -n "${PROG:-$APPNAME}" ] && [ -n "$(get_desc)" ] && printf_help "    $(get_desc)" 6 || printf_help "$1" "${2:-10}"; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# begin
printf_descr ""
printf_help 'Usage: ask_yes_no_question "Message to user" "command"' "5"
printf_help "-v, --version          -  display version"
printf_help "-h, --help             -  display help"

# end help
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#exit "${exitCode:-1}"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end

