#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "2" "A simple home automation script"
printf_help "4" "automate pause   |   turn hue lights on/off and play/pause roku"
printf_help "4" "automate play    |   turn hue lights off and play roku"
printf_help "4" "automate stop    |   turn hue lights on and stop roku"
printf_help "4" "automate toggle  |   same as pause"
