printf_help "Usage:"
printf_help "QUERY                               process QUERY and exit"
printf_help "--help                              show this help"
printf_help "--shell [LANG]                      shell mode (open LANG if specified)"
printf_help "--standalone-install [DIR|help]     install cheat.sh in the standalone mode (by default, into ~/.config/cheat.sh)"
printf_help "--mode [auto|lite]                  set (or display) mode of operation"
printf_help "                                    * auto - prefer the local installation"
printf_help "                                    * lite - use the cheat sheet server"
