#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "Setup a development enviroment"
printf_help "4" "By default this will try to guess"
printf_help "4" "the current project and set it up"
printf_help "4" "Usage: devenv project | devenv node"
printf_help "4" "The current enviroments are as follows:"
printf_help "4" "$APPNAME jekyll"
printf_help "4" "$APPNAME ruby"
printf_help "4" "$APPNAME python"
printf_help "4" "$APPNAME perl"
printf_help "4" "$APPNAME php"
printf_help "4" "$APPNAME node"
printf_help "4" "$APPNAME vue"
printf_help "4" "$APPNAME react"
printf_help "4" "$APPNAME express"
printf_help "4" "$APPNAME create-project"
printf_help "4" "$APPNAME mevn"
printf_help "4" "$APPNAME gen-shellrc"
