#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "Setup a development enviroment"
printf_help "4" "By default this will try to guess"
printf_help "4" "the current project and set it up"
printf_help "4" "Usage: devenv project | devenv node"
printf_help "4" "The current enviroments are as follows:"
printf_help "4" "devenv jekyll"
printf_help "4" "devenv ruby"
printf_help "4" "devenv python"
printf_help "4" "devenv perl"
printf_help "4" "devenv php"
printf_help "4" "devenv node"
printf_help "4" "devenv vue"
printf_help "4" "devenv react"
printf_help "4" "devenv express"
printf_help "4" "devenv create-project"
printf_help "4" "devenv mevn"
printf_help "4" "devenv gen-shellrc"
