#!/usr/bin/env bash
source ./.functions
printf_help "4" "A DotFiles Manager for all systems   |   Usage: dfmgr command"
printf_help "4" "dfmgr version              - show the version info           | IE: dfmgr version bash"
printf_help "4" "dfmgr available            - list available dotfiles         | IE: dfmgr available"
printf_help "4" "dfmgr list                 - list installed dotfiles         | IE: dfmgr list"
printf_help "4" "dfmgr search               - find a dotfile                  | IE: dfmgr search geany"
printf_help "4" "dfmgr install              - install a dotfile               | IE: dfmgr install vim"
printf_help "4" "dfmgr update               - update the dotfiles             | IE: dfmgr update"
printf_help "4" "dfmgr personal             - update personal dotfiles        | IE: dfmgr personal"
