#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "A DotFiles Manager for all systems   |   Usage: dfmgr command"
printf_help "4" "dfmgr version              - show the version info           | IE: dfmgr version bash"
printf_help "4" "dfmgr available            - list available dotfiles         | IE: dfmgr available"
printf_help "4" "dfmgr list                 - list installed dotfiles         | IE: dfmgr list"
printf_help "4" "dfmgr search               - find a dotfile                  | IE: dfmgr search geany"
printf_help "4" "dfmgr install              - install a dotfile               | IE: dfmgr install vim"
printf_help "4" "dfmgr update               - update the dotfiles             | IE: dfmgr update"
printf_help "4" "dfmgr personal             - update personal dotfiles        | IE: dfmgr personal"
