#!/usr/bin/env bash
source ./.functions
printf_help "4" '           🙄😆 emojify - emojis on the command line 😱😄'
printf_help "4" '-h|help|-help|--help        | This help!                  | emojis help'
printf_help "4" '-s|search|-search|--search  | search for an emoji         | emojis search smile'
printf_help "4" '-l|list|-list|--list        | list all available emojis   | emojis list'
printf_help "4" '-p|print|-print|--print     | print to console            | emojis print "Hello :smile:" '
printf_help "4" '-update|update|--update     | update emojify              | emojis update'
