#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" '           🙄😆 emojify - emojis on the command line 😱😄'
printf_help "4" '-h|help|-help|--help        | This help!                  | emojis help'
printf_help "4" '-s|search|-search|--search  | search for an emoji         | emojis search smile'
printf_help "4" '-l|list|-list|--list        | list all available emojis   | emojis list'
printf_help "4" '-p|print|-print|--print     | print to console            | emojis print "Hello :smile:" '
printf_help "4" '-update|update|--update     | update emojify              | emojis update'
