#!/usr/bin/env bash
source ./.functions
printf_help "4" "A Package Manager for all systems   |   Usage: sudo fontmgr command"
printf_help "4" "fontmgr version              - show the version info          | IE: fontmgr version Hack"
printf_help "4" "fontmgr makecache            - update font cache              | IE: fontmgr makecache"
printf_help "4" "fontmgr list                 - list all installable fonts     | IE: fontmgr list"
printf_help "4" "fontmgr list-installed       - list installed fonts           | IE: fontmgr list-installed"
printf_help "4" "fontmgr search               - find font                      | IE: fontmgr search font"
printf_help "4" "fontmgr search-installed     - search installed fonts         | IE: fontmgr search-installed font"
printf_help "4" "fontmgr install              - install a font                 | IE: fontmgr install font"
printf_help "4" "fontmgr remove               - remove a font                  | IE: fontmgr remove font"
printf_help "4" "fontmgr update               - update the fonts               | IE: fontmgr update"
