#!/usr/bin/env bash
source ./.functions
printf_help "4" "Generate a human-readable change log from a git repo"
printf_help "4" "Usage:"
printf_help "4" "git-changelog [options]"
printf_help "4" "git-changelog --help | -h"
printf_help "4" "git-changelog --version | -v"
