#!/usr/bin/env bash
source ./.functions
printf_help "4" "The Default action is to clone/pull"
printf_help "4" "Usage:"
printf_help "4" "--single username reponame"
printf_help "4" "--org username"
printf_help "4" "--user usename"
printf_help "4" "--push to push the repos or"
printf_help "4" "--clone to clone/update local repos"
printf_help "4" "--help --org --user --push"
printf_help "4" "--clone --pull --create"
printf_help "4" "--delete --gist"
