#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "The Default action is to clone/pull"
printf_help "4" "Usage:"
printf_help "4" "--single username reponame"
printf_help "4" "--org username"
printf_help "4" "--user usename"
printf_help "4" "--push to push the repos or"
printf_help "4" "--clone to clone/update local repos"
printf_help "4" "--help --org --user --push"
printf_help "4" "--clone --pull --create"
printf_help "4" "--delete --gist"
