#!/usr/bin/env bash
source ./.functions
printf_help "4" "Usage:"
printf_help "4" "init: Default init message"
printf_help "4" "alot: I'm to lazy to say"
printf_help "4" "docker, node, ruby, php, perl, python, bug, fixes"
printf_help "4" "Also -m --message or custom to say your own messsage"
