#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "          A Package Manager for all systems   |   Usage: sudo iconmgr command"
printf_help "4" "iconmgr version              - show the version info          | IE: iconmgr version N.I.B."
printf_help "4" "iconmgr makecache            - update icon cache              | IE: iconmgr makecache"
printf_help "4" "iconmgr list                 - list all installable icons     | IE: iconmgr list"
printf_help "4" "iconmgr list-installed       - list installed icons           | IE: iconmgr list-installed"
printf_help "4" "iconmgr search               - find icon                      | IE: iconmgr search icon"
printf_help "4" "iconmgr search-installed     - search installed icons         | IE: iconmgr search-installed icon"
printf_help "4" "iconmgr install              - install a icon                 | IE: iconmgr install icon"
printf_help "4" "iconmgr remove               - remove a icon                  | IE: iconmgr remove icon"
printf_help "4" "iconmgr update               - update the icons               | IE: iconmgr update"
