#!/usr/bin/env bash
source ./.functions
printf_help "4" "If This Then That - run webhooks from command"
printf_help "4" "The way I use this is webhook_name message address/link"
printf_help "4" "Usage: $APPNAME webhook_name webhook_value1 webhook_value2"
printf_help "4" "This requires an api key and the enviroment variable IFTTT_ACCESS_TOKEN to be set"
printf_help "4" "Get an API key from ifttt maker site: https://ifttt.com/maker_webhooks/settings"
