#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "If This Then That - run webhooks from command"
printf_help "4" "The way I use this is webhook_name message address/link"
printf_help "4" "Usage: $APPNAME webhook_name webhook_value1 webhook_value2"
printf_help "4" "This requires an api key and the enviroment variable IFTTT_ACCESS_TOKEN to be set"
printf_help "4" "Get an API key from ifttt maker site: https://ifttt.com/maker_webhooks/settings"
