#!/usr/bin/env bash
source ./.functions
printf_help "4" "Add these 2 lines to ${auth_path}, modify the values for your info and save it:"
printf_help "4" 'export GITHUB_USERNAME="yourname" '
printf_help "4" 'export GITHUB_PERSONAL_ACCESS_TOKEN="youraccesstoken" '
printf_help "4" "Add your list of GitHub repos to ${github_path}."
printf_help "4" "Separate out each entry on a new line and only include the owner/repo."
printf_help "4" "Here's an example of what that file could look like:"
printf_help "4" "pallets/flask"
printf_help "4" "phoenixframework/phoenix"
