#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "A simple logging utility"
printf_help "4" "Usage       : log mycommand"
printf_help "4" "-name       : custom log name"
printf_help "4" "--clean     : remove old logs"
printf_help "4" "--show      : will show all output"
printf_help "4" "--silent    : no output"
printf_help "4" "--err       : show only error"
printf_help "4" "--noerr     : hide error mesaages"
printf_help "4" "--list      : list all logs"
printf_help "4" "--open      : open logdir"
printf_help "2" "Default logdir: $LOGDIR/logr"
