#!/usr/bin/env bash
source ./.functions
printf_help "4" "A simple logging utility"
printf_help "4" "Usage       : log mycommand"
printf_help "4" "--clean     : remove old logs"
printf_help "4" "--show      : will show all output"
printf_help "4" "--silent    : no output"
printf_help "4" "--err       : show only error"
printf_help "4" "--noerr     : hide error mesaages"
printf_help "4" "--list      : list all logs"
printf_help "4" "--open      : open logdir"
