#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "4" "Convert metric to imperial measurements"
printf_help "4" "Convert celcius to fahrenheit     | $APPNAME f 20"
printf_help "4" "Convert millimeter to inches      | $APPNAME mm 20"
printf_help "4" "Convert centimeter to inches      | $APPNAME cm 20"
printf_help "4" "Convert meter to feet             | $APPNAME m 20"
printf_help "4" "Convert kilometer to miles        | $APPNAME km 20"
