#!/usr/bin/env bash
source ./.functions
printf_help "4" "mpd client script"
printf_help "4" "If you have the MPDSERVER variable set then"
printf_help "4" "this will connect to the remote MPD server"
printf_help "4" "otherwise it will connect to the local MPD"
