#!/usr/bin/env bash
source ./.functions
printf_help "4" "Usage: mydate nowtime         |  get current time"
printf_help "4" "Usage: mydate nowdate         |  get current date"
printf_help "4" "Usage: mydate setver          |  set version"
printf_help "4" "Usage: mydate setverfile      |  out to ./verion.txt"
