#!/usr/bin/env bash
source ./.functions
printf_help "4" "Usage:"
printf_help "4" "myip              |   print current ip addresses"
printf_help "4" "myip local        |   print current local ip address"
printf_help "4" "myip public       |   print current public ip address"
printf_help "4" "myip local 4      |   print current local ip 4 address"
printf_help "4" "myip local 6      |   print current local ip 6 address"
printf_help "4" "myip public 4     |   print current public ip 4 address"
printf_help "4" "myip public 4     |   print current public ip 4 address"
