#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "Usage:"
printf_help "4" "myip              |   print current ip addresses"
printf_help "4" "myip local        |   print current local ip address"
printf_help "4" "myip public       |   print current public ip address"
printf_help "4" "myip local 4      |   print current local ip 4 address"
printf_help "4" "myip local 6      |   print current local ip 6 address"
printf_help "4" "myip public 4     |   print current public ip 4 address"
printf_help "4" "myip public 4     |   print current public ip 4 address"
