#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "Usage: "
printf_help "4" "notes something you want to jot down |   appends that text to the file"
printf_help "4" "xclip -o | notes                     |   appends your clipboard to the file"
printf_help "4" "notes                                |   opens the file in your editor $EDITOR"
