#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "2" "                 A simple notes app written in bash                   "
printf_help "4" "notes                                |   Opens the file in vim"
printf_help "4" "notes something you want to jot down |   Appends that text to the file"
printf_help "4" "xclip -o | notes or notes -          |   Appends stdin to the file"
printf_help "4" "notes client                         |   used to send notes to the server - same syntax as notes"
printf_help "4" "notes service                        |   Run notes as a server using netcat"
printf_help "4" "notes service --status               |   Shows the current status of the server"
printf_help "4" "notes service --kill                 |   Initiates the kill to stop the server"
printf_help "4" "notes service systemd                |   Systemd functions"
printf_help "4" "notes service systemd install        |   Installs notes as a service using systemd"
printf_help "4" "notes service systemd remove         |   Remove the notes systemd service"
printf_help "4" "notes service systemd start          |   Start the notes systemd service"
printf_help "4" "notes service systemd stop           |   Stop the notes systemd service"
printf_help "4" "notes service systemd restart        |   Restart the notes systemd service"
printf_help "4" "notes service systemd status         |   Get the notes systemd service status"
printf_help "4" "notes service systemd run/vars       |   Used by systemd to run the notes server"
printf_help "4" "notes config                         |   Generates the configuration file"
printf_help "3" "All variable can be overwritten by editingthe file ~/.config/notes/config"
