#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "pb; a command line pastebin service helper"
printf_help "4" "usage: pb <service> [file|stream]"
printf_help "4" " "
printf_help "4" "services:"
printf_help "4" "   0x0.st, catbox.moe, clbin.com, dmca.gripe,"
printf_help "4" "   dumpz.org, fiery.me, ix.io, p.iotek.org,"
printf_help "4" "   pastebin.com, sprunge.us, uguu.se, w1r3.net"
printf_help "4" ""
printf_help "4" "environment variables:"
printf_help "4" "   UA: user-agent string (defaults to some chrome one)"
printf_help "4" " "
printf_help "4" "envs for pastebin.com:"
printf_help "4" "   PB_API_DEV: developer api key [required] https://pastebin.com/api#1"
printf_help "4" "   PB_API_USR: user api key [optional] https://pastebin.com/api#8"
printf_help "4" "   PRIVACY: paste visibility  [optional] valid values: public|0, unlisted|1, private|2"
printf_help "4" "   ANON: paste w/o a user key even if defined [optional]"
printf_help "4" " "
printf_help "4" "examples:"
printf_help "4" "   pb ix ~/.vimrc"
printf_help "4" "   pb 0x0 <(ps aux)"
printf_help "4" "   dmesg | pb iop"
printf_help "4" "   PB_API_DEV=XXXX PRIVACY=0 pb pb /tmp/leak.txt"
