#!/usr/bin/env bash
source ./.functions
printf_help "4" 'Usage: post2social "Your message" '
printf_help "4" 'post2social twitter "Your message" '
printf_help "4" 'post2social mastodon "Your message" '
