#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "-a    |    Show hidden files/directories."
printf_help "4" "-r    |    Show file content in the right."
printf_help "4" "-u    |    Show file content under the list."
printf_help "4" "-d    |    Show content of the directory."
printf_help "4" "-D    |    Do not show content of the directory."
printf_help "4" "-n    |    No preview."
printf_help "4" "-C    |    No confirmation at deletion."
printf_help "4" "-h    |    print this help and exit."
