#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "-d, --debug           enable debugging"
printf_help "4" "--no-systray          do not create system tray icon"
printf_help "4" "-t TIMEOUT            timeout in seconds"
printf_help "4" "-p                    set vertical position"
printf_help "4" "--persist             make window persistent"
printf_help "4" "-s                    set font size"
printf_help "4" "-g GEOMETRY           set fixed area/window geometry"
printf_help "4" "--key-mode            set key processing mode"
printf_help "4" "--bak-mode            backspace processing mode"
printf_help "4" "--mods-mode           {normal,emacs,mac,win,tux}"
printf_help "4" "-m, --mods-only       show only keys with modifiers pressed"
printf_help "4" "--multiline           span text over multiple lines"
printf_help "4" "--vis-shift           always show Shift when modifiers are pressed"
printf_help "4" "--no-whitespace       disable visualization of whitespace"
printf_help "4" "--show-settings       show settings dialog on start"
printf_help "4" "--scr SCREEN          show on the specified screen number"
printf_help "4" "-f FONT_DESC          set font family/weight"
printf_help "4" "--font-color          set font color"
printf_help "4" "--bg-color BG_COLOR   background color"
printf_help "4" "--opacity OPACITY     window opacity (in range 0.0-1.0)"
printf_help "4" "--ignore KeySym       Ignore the specified KeySym"
printf_help "4" "--compr-cnt COUNT     Compress key repeats after the specified count"
printf_help "4" "--start-disabled      do not display anything until explicitly requested"
printf_help "4" "--version             show version of screenkey"
printf_help "4" "-M, --mouse           show the mouse buttons"
