#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "Username       |    Change ssh username to 'GUEST"
printf_help "4" "ls   -la       |    List Files"
printf_help "4" "free -h        |    Show free memory"
printf_help "4" "df   -ih       |    Show free inodes"
printf_help "4" "df   -h        |    Show free disk space"
printf_help "4" "Info           |    Full system info"
printf_help "4" "Sshkey         |    Add my ssh key to 'target'"
printf_help "4" "Alias          |    Add my usefull aliases to 'target'"
printf_help "4" "Copy           |    Copy selected file or dir to 'target'"
printf_help "4" "Dest           |    Change destination folder 'DEST' on 'target'"
printf_help "4" "Upload         |    Upload file or folder from 'PWD' to 'target: '{DEST}'"
printf_help "4" "Download       |    Download file or folder from 'target:' '{DEST} to 'PWD'"
printf_help "4" "Local          |    Change local port 'LOCAL'"
printf_help "4" "Remote         |    Change remote port 'REMOTE'"
printf_help "4" "Tunnel         |    Start portunneling from target port REMOTE to local port LOCAL"
