#!/usr/bin/env bash
source ./.functions
printf_help "4" "Usage:"
printf_help "4" "sudoers insults        |   Create insults file"
printf_help "4" "sudoers adduser user   |   add user to sudo"
printf_help "4" "sudoers remuser user   |   remove user from sudo"
printf_help "4" "sudoers remove         |   remove yourself from sudo"
printf_help "4" "sudoers pass           |   require password for sudo"
printf_help "4" "sudoers nopass         |   don't require a password for sudo"
