#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "A Package Manager for all systems   |   Usage: sudo systemmgr command"
printf_help "4" "systemmgr version              - show the version info      | IE: systemmgr version tor"
printf_help "4" "systemmgr list                 - list installed packages    | IE: systemmgr list"
printf_help "4" "systemmgr search               - search for a package       | IE: systemmgr search postfix"
printf_help "4" "systemmgr install              - install a package          | IE: systemmgr install cron"
printf_help "4" "systemmgr remove               - remove a package           | IE: systemmgr remove tor"
printf_help "4" "systemmgr update               - update a package           | IE: systemmgr update"
