printf_help "Usage: tasks.sh [task_num] [command] ..."
printf_help "list [all|complete]       - shows a list of tasks"
printf_help "add [@project] desc       - adds a task to the given project"
printf_help "<task_num> delete         - deletes a task and all its sessions"
printf_help "<task_num> start          - starts a session for the given task"
printf_help "[task_num] stop [durn]    - stops session(s) with optional duration"
printf_help "<task_num> session <durn> - creates a session"
printf_help "<task_num> switch [durn]  - switches session to a new task"
printf_help "<task_num> done [durn]    - marks a task as complete"
printf_help "<task_num> [info]         - shows information for the given task"
printf_help "report [week]             - generate a weekly report"
printf_help "cleanup                   - discard all completed tasks"
