#!/usr/bin/env bash
source ./.functions
printf_help "4" "A Package Manager for all systems   |   Usage: sudo thememgr command"
printf_help "4" "thememgr makecache            - update theme cache              | IE: thememgr makecache"
printf_help "4" "thememgr list                 - list all installable themes     | IE: thememgr list"
printf_help "4" "thememgr list-installed       - list installed themes           | IE: thememgr list-installed"
printf_help "4" "thememgr search               - find theme                      | IE: thememgr search theme"
printf_help "4" "thememgr search-installed     - search installed themes         | IE: thememgr search-installed theme"
printf_help "4" "thememgr install              - install a theme                 | IE: thememgr install theme"
printf_help "4" "thememgr remove               - remove a theme                  | IE: thememgr remove theme"
printf_help "4" "thememgr update               - update the themes               | IE: thememgr update"
