#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "A Package Manager for all systems   |   Usage: sudo thememgr command"
printf_help "4" "thememgr makecache            - update theme cache              | IE: thememgr makecache"
printf_help "4" "thememgr list                 - list all installable themes     | IE: thememgr list"
printf_help "4" "thememgr list-installed       - list installed themes           | IE: thememgr list-installed"
printf_help "4" "thememgr search               - find theme                      | IE: thememgr search theme"
printf_help "4" "thememgr search-installed     - search installed themes         | IE: thememgr search-installed theme"
printf_help "4" "thememgr install              - install a theme                 | IE: thememgr install theme"
printf_help "4" "thememgr remove               - remove a theme                  | IE: thememgr remove theme"
printf_help "4" "thememgr update               - update the themes               | IE: thememgr update"
