#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help 'Usage: '$APPNAME' "ProjectName"  |  '$APPNAME' "MyNewApp"'
printf_help "4" "$APPNAME git       | Create a git repo and keep changes via git "
printf_help "4" "$APPNAME list      | List all todos "
printf_help "4" "$APPNAME archive   | Archive the current todo "
printf_help "4" "$APPNAME open      | Open the current todo "
printf_help "4" "$APPNAME todoname  | Will take all input and create a todo "
