#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "              A Wallpaper Manager for all systems   |   Usage: wallpapermgr command"
printf_help "4" "wallpapermgr version              - show the version info           | IE: wallpapermgr version casjay"
printf_help "4" "wallpapermgr remove               - remove wallpaper pack           | IE: wallpapermgr remove casjay"
printf_help "4" "wallpapermgr install              - install wallpaper pack          | IE: wallpapermgr install dwt1"
printf_help "4" "wallpapermgr update               - update wallpaper pack           | IE: wallpapermgr update"
