#!/usr/bin/env bash
source ./.functions
printf_help "4" "Weather in your terminal"
printf_help "4" "https://github.com/chubin/wttr.in"
printf_help "4" "IE: weather option 90210 or weather city lax"
printf_help "4" "Options are as follows:"
printf_help "4" "city use zipcode or airport code        | weather report for city"
printf_help "4" "v2 use zipcode or airport code          | version 2 of wttr.in"
printf_help "4" "img use city or closest airport code    | create an image file"
printf_help "4" "moon                                    | get moon phase"
printf_help "4" "Run weather :help                       | see all options"
printf_help "4" "weather for defaults and detected location"
