#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "Weather in your terminal"
printf_help "4" "https://github.com/chubin/wttr.in"
printf_help "4" "IE: weather option 90210 or weather city lax"
printf_help "4" "Options are as follows:"
printf_help "4" "city use zipcode or airport code        | weather report for city"
printf_help "4" "v2 use zipcode or airport code          | version 2 of wttr.in"
printf_help "4" "img use city or closest airport code    | create an image file"
printf_help "4" "moon                                    | get moon phase"
printf_help "4" "Run weather :help                       | see all options"
printf_help "4" "weather for defaults and detected location"
