#!/usr/bin/env bash
# _template_completions completion
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# template for template

_template_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="--help --config --version"

  _init_completion || return

  case $prev in
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return 0
    ;;
  esac
} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _template_completions -o default template

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
