#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME="GEN_SCRIPT_REPLACE_FILENAME"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#REPLACE_THIS_WITH_HEADER_INFO
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
printf_help() {
  printf "%b" "$(tput setaf "${2:-4}" 2>/dev/null)" "\t\t$1" "$(tput sgr0 2>/dev/null)"
  printf '\n'
}
get_desc() {
  local PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/usr/sbin"
  local appname="$(type -P "${PROG:-$APPNAME}" 2>/dev/null || command -v "${PROG:-$APPNAME}" 2>/dev/null)"
  local desc="$(grep ^"# @Description" "$appname" 2>/dev/null | grep ' : ' | sed 's#..* : ##g' | grep '^')"
  if [ -n "$desc" ]; then printf '%s' "$desc"; else return 1; fi
}
printf_descr() { if [ -n "${PROG:-$APPNAME}" ] && [ -n "$(get_desc)" ]; then
  printf_color "    $(get_desc)" 6
else printf_help "$1" "${2:-10}"; fi; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# begin
printf_descr "    GEN_SCRIPT_REPLACE_DESC"
printf_help "Usage: GEN_SCRIPT_REPLACE_FILENAME " "5"
printf_help ""
printf_help "-v, --version           -  display version"
printf_help "-h, --help              -  display help"

# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#exit "${exitCode:-1}"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end
