#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
PROG="GEN_SCRIPT_GEN_SCRIPT_REPLACE_FILENAME"
USER="${SUDO_USER:-${USER}}"
HOME="${USER_HOME:-${HOME}}"
SRC_DIR="${BASH_SOURCE%/*}"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#set opts

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : GEN_SCRIPT_GEN_SCRIPT_REPLACE_VERSION
# @Author        : GEN_SCRIPT_GEN_SCRIPT_REPLACE_AUTHOR
# @Contact       : GEN_SCRIPT_GEN_SCRIPT_REPLACE_EMAIL
# @License       : GEN_SCRIPT_GEN_SCRIPT_REPLACE_LICENSE
# @ReadME        : GEN_SCRIPT_GEN_SCRIPT_REPLACE_FILENAME --help
# @Copyright     : GEN_SCRIPT_GEN_SCRIPT_REPLACE_COPYRIGHT
# @Created       : GEN_SCRIPT_GEN_SCRIPT_REPLACE_DATE
# @File          : GEN_SCRIPT_GEN_SCRIPT_REPLACE_FILENAME
# @Description   : GEN_SCRIPT_GEN_SCRIPT_REPLACE_DESC
# @TODO          : GEN_SCRIPT_GEN_SCRIPT_REPLACE_TODO
# @Other         : GEN_SCRIPT_GEN_SCRIPT_REPLACE_OTHER
# @Resource      : GEN_SCRIPT_GEN_SCRIPT_REPLACE_RES
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# begin
printf_help "2" 'REPLACE _FILENAME help file'
printf_help "4" "Usage: GEN_SCRIPT_GEN_SCRIPT_REPLACE_FILENAME  |  "
