#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : REPLACE_VERSION
# @Author        : REPLACE_AUTHOR
# @Contact       : REPLACE_EMAIL
# @License       : REPLACE_LICENSE
# @Copyright     : REPLACE_COPYRIGHT
# @Created       : REPLACE_DATE
# @File          : REPLACE_FILENAME
# @Description   : REPLACE_DESC
# @TODO          : REPLACE_TODO
# @Other         : REPLACE_OTHER
# @Resource      : REPLACE_RES
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_REPLACE_FILENAME() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local OPTS="--help --version"
  local ARRAY=""

  _init_completion || return

  if [[ ${cur} == -* ]] ; then
    COMPREPLY=( $(compgen -W '${OPTS}' -- ${cur}) )
  else
  case $prev in
  *)
    COMPREPLY=($(compgen -W '$(_filedir)' -- "${cur}"))
    return 0
    ;;
  esac
  fi
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _REPLACE_FILENAME REPLACE_FILENAME
