#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : GEN_SCRIPT_REPLACE_VERSION
# @Author        : GEN_SCRIPT_REPLACE_AUTHOR
# @Contact       : GEN_SCRIPT_REPLACE_EMAIL
# @License       : GEN_SCRIPT_REPLACE_LICENSE
# @ReadME        : GEN_SCRIPT_REPLACE_FILENAME --help
# @Copyright     : GEN_SCRIPT_REPLACE_COPYRIGHT
# @Created       : GEN_SCRIPT_REPLACE_DATE
# @File          : GEN_SCRIPT_REPLACE_FILENAME
# @Description   : GEN_SCRIPT_REPLACE_DESC
# @TODO          : GEN_SCRIPT_REPLACE_TODO
# @Other         : GEN_SCRIPT_REPLACE_OTHER
# @Resource      : GEN_SCRIPT_REPLACE_RES
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_GEN_SCRIPT_REPLACE_FILENAME() {
  local cur prev words cword CONFFILE CONFDIR SEARCHDIR CASJAYSDEVDIR FUNCTIONSDIR SEARCHCMD SHOW_COMP_OPTS DEFAULTOPTS
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/misc/settings/GEN_SCRIPT_REPLACE_FILENAME"
  local OPTSDIR="$HOME/.local/share/misc/options/GEN_SCRIPT_REPLACE_FILENAME"
  local SEARCHDIR="$HOME/.config/misc/settings/GEN_SCRIPT_REPLACE_FILENAME"
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local FUNCTIONSDIR="${HOME/.local/share/CasjaysDev/functions}"
  local DEFAULTOPTS="$(GEN_SCRIPT_REPLACE_FULLFILENAME -a || echo -v -h -a)"
  local DEFAULTARRAY="$(GEN_SCRIPT_REPLACE_FULLFILENAME -l || echo )"
  local SEARCHCMD="$(find -L $SEARCHDIR -maxdepth 3 -type f | sed 's#'$CONFDIR/'##g' | grep '^' || return 1)"
  local SHOW_COMP_OPTS=""
  local SHORTOPTS=""
  local LONGOPTS=""
  local ARGS="${DEFAULTOPTS} ${SHORTOPTS} ${LONGOPTS}"
  local ARRAY=""

  _init_completion || return

  if [ "$SHOW_COMP_OPTS" != "" ]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi

  if [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${ARGS}' -- ${cur}))
  else
    case $prev in
      *)
       if [ -n "$FILEDIR" ]; then
          _filedir
      fi
      if [[ "$ARRAY" = "show-commands" ]]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [[ "$ARRAY" = "show-none" ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [[ "$ARRAY" = "show-_filedir" ]]; then
        _filedir
      elif [[ -n "$ARRAY" ]]; then
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [[ -n "$OPTS" ]]; then
        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      fi
      return 0
      ;;
    esac
  fi
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _GEN_SCRIPT_REPLACE_FILENAME GEN_SCRIPT_REPLACE_FILENAME

