#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : blog --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : blog
# @Description   : autocomplete for blog
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_blog() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword split
  local BLOG_DIR="${BLOG_DIR:-$HOME/.local/share/blog}"
  ARRAY="new page post edit config -c --help"
  _init_completion || return

  list_all() {
    COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
  }

  local special i
  for ((i = 1; i < ${#words[@]} - 1; i++)); do
    if [[ ${words[i]} == @(edit) ]]; then
      special=${words[i]}
      break
    fi
  done

  if [[ -v special ]]; then
    if [[ $cur == @(*/|[.~])* && \
      $special == @(edit) ]]; then
      list_all
      return
    fi

    case $special in
    edit)
      k=0
      i="$BLOG_DIR/_{posts,pages}/*"
      for j in $(compgen -f "$i/$cur"); do
        [ -d "$j" ] && j="${j}"
        COMPREPLY[k++]=${j#$i/}
      done
      return 0
      ;;
    esac
  fi

  # relevant options completion

  case $prev in
  -c)
    COMPREPLY=($(compgen -W '$(cd ~/.config/blog && find -iname '*' || return 1)' -- "$cur"))
    return
    ;;
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    ;;
  esac

  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _blog -o default blog
