#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : config --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : config
# @Description   : autocomplete for config
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_config() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local prev="${COMP_WORDS[COMP_CWORD - 1]}"
  local ARRAY="$(<$CASJAYSDEVDIR/scripts/helpers/config/array)"
  local LIST="$(<$CASJAYSDEVDIR/scripts/helpers/config/list)"
  _init_completion || return

  case $prev in
  help | h | --h*)
    return
    ;;

  add)
    COMPREPLY=($(compgen -W '$(_filedir)' -- "$cur"))
    return
    ;;

  commit)
    COMPREPLY=($(compgen -W '$(git --git-dir="$HOME/.local/dotfiles/config/" --work-tree="$HOME" commit)' -- "$cur"))
    return
    ;;

  pull)
    COMPREPLY=($(compgen -W '$(git --git-dir="$HOME/.local/dotfiles/config/" --work-tree="$HOME" pull)' -- "$cur"))
    return
    ;;

  set)
    COMPREPLY=($(compgen -W '$(git --git-dir="$HOME/.local/dotfiles/config/" --work-tree="$HOME" config)' -- "$cur"))
    return
    ;;

  status)
    COMPREPLY=($(compgen -W '$(git --git-dir="$HOME/.local/dotfiles/config/" --work-tree="$HOME" status)' -- "$cur"))
    return
    ;;

  push)
    COMPREPLY=($(compgen -W '--set-upstream origin master -f' -- "$cur"))
    return
    ;;

  log)
    return
    ;;

  init)
    return
    ;;

  esac

  COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _config -o default config &&
  complete -F _git -o default config
