#!/usr/bin/env bash
# _dfmgr_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for dfmgr

_dfmgr_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="$(cat ${SCRIPTSFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}/helpers/dfmgr/array)"
  local LIST="$(cat ${SCRIPTSFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}/helpers/dfmgr/list)"

  _init_completion || return

  case $prev in
  help | h | --h*)
    return
    ;;
  install | update | remove)
    COMPREPLY=($(compgen -W '${LIST}' -- "$cur"))
    return
    ;;
  *)
    COMPREPLY=($(compgen -W '${LIST}' -- "$cur"))
    ;;

  esac

  COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))

} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # enable completions
  complete -F _dfmgr_completions -o default dfmgr

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
