#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : dockermgr --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : dockermgr
# @Description   : autocomplete for dockermgr
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_dockermgr() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword split
  local ARRAY="$(<$CASJAYSDEVDIR/helpers/dockermgr/array)"
  local LIST="$(<$CASJAYSDEVDIR/helpers/dockermgr/list)"

  _init_completion -s || return

  list_all() {
    COMPREPLY=($(compgen -W '${LIST}' -- "$cur"))
  }

  local special i
  for ((i = 1; i < ${#words[@]} - 1; i++)); do
    if [[ ${words[i]} == @(install|update|remove) ]]; then
      special=${words[i]}
      break
    fi
  done

  if [[ -v special ]]; then
    if [[ $cur == @(*/|[.~])* && \
      $special == @(|install|update|remove) ]]; then
      list_all
      return
    fi

    case $special in
    install)
      list_all
      return
      ;;
    update)
      k=0
      i="$HOME/.local/share/CasjaysDev/apps/dockermgr"
      for j in $(compgen -f "$i/$cur"); do
        [ -d "$j" ] && j="${j}"
        COMPREPLY[k++]=${j#$i/}
      done
      return 0
      ;;
    remove)
      list_all
      return
      ;;
    esac
  fi

  case $prev in
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    ;;
  esac

  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _dockermgr -o default dockermgr
