#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : dotfiles --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : dotfiles
# @Description   : autocomplete for dotfiles
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_dotfiles() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local ARRAY="$(<$CASJAYSDEVDIR/helpers/dotfiles/array)"
  local LIST="$(<$CASJAYSDEVDIR/helpers/dotfiles/list)"
  local ADMIN="$(<$CASJAYSDEVDIR/helpers/dotfiles/admin)"
  local STOW="$(<$CASJAYSDEVDIR/helpers/config/array)"
  local LSBIN="$(ls $CASJAYSDEVDIR/bin/)"

  _init_completion || return

  case $prev in
  help | h | --h*)
    return
    ;;

  admin)
    COMPREPLY=($(compgen -W '--all ${ADMIN[*]}' -- "${cur[*]}"))
    return
    ;;

  install)
    COMPREPLY=($(compgen -W '--all ${LIST[*]}' -- "$cur"))
    return
    ;;

  stow)
    COMPREPLY=($(compgen -W ' ${STOW[*]}' -- "$cur"))
    return
    ;;

  config)
    COMPREPLY=($(compgen -W 'dircolors' -- "$cur"))
    return
    ;;

  update)
    COMPREPLY=($(compgen -W ' ${LIST[*]}' -- "$cur"))
    return
    ;;

  describe)
    COMPREPLY=($(compgen -W ' ${LSBIN}' -- "$cur"))
    ;;

  version)
    COMPREPLY=($(compgen -W ' ${LIST[*]} ${ADMIN[*]}' -- "$cur"))
    return
    ;;

  *)
    COMPREPLY=($(compgen -W ' ${LIST[*]}' -- "$cur"))
    ;;

  esac
  COMPREPLY=($(compgen -W '${ARRAY[*]}' -- "$cur"))
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _dotfiles -o default dotfiles
