#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : emojis --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : emojis
# @Description   : autocomplete for emojis
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_emojis() {
  local cur prev words cword
  local ARRAY="$(</usr/local/share/CasjaysDev/scripts/helpers/emojis/array)"
  local LIST="$(</usr/local/share/CasjaysDev/scripts/helpers/emojis/list)"
  _init_completion || return

  case $prev in
  -l | list | -list | --list)
    COMPREPLY=($(compgen -W '${LIST}' -- "$cur"))
    return
    ;;
  *)
    COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _emojis -o default emj &&
  complete -F _emojis -o default emojis
