#!/usr/bin/env bash
# _fontmgr_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for fontmgr

_fontmgr_completions() {
  local cur prev words cword
  local prefix=fontmgr
  local ARRAY="$(cat ${SCRIPTSFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}/helpers/$prefix/array)"
  local LIST="$(cat ${SCRIPTSFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}/helpers/$prefix/list)"

  local cur prev words cword split
  _init_completion -s || return

  list_all() {
    COMPREPLY=($(compgen -W '${LIST}' -- "$cur"))
  }

  local special i
  for ((i = 1; i < ${#words[@]} - 1; i++)); do
    if [[ ${words[i]} == @(install|update|remove) ]]; then
      special=${words[i]}
      break
    fi
  done

  if [[ -v special ]]; then
    if [[ $cur == @(*/|[.~])* && \
      $special == @(|install|update|remove) ]]; then
      list_all
      return
    fi

    case $special in
    install)
      list_all
      return
      ;;
    update)
      k=0
      i="$HOME/.local/share/CasjaysDev/apps/$prefix"
      for j in $(compgen -f "$i/$cur"); do
        [ -d "$j" ] && j="${j}"
        COMPREPLY[k++]=${j#$i/}
      done
      return 0
      ;;
    remove)
      list_all
      return
      ;;
    esac
  fi

  case $prev in
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    ;;
  esac

  $split && return

} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # enable completions
  complete -F _fontmgr_completions -o default fontmgr

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
