#!/usr/bin/env bash
# _fontmgr_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for fontmgr

_fontmgr_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="$(cat ${SCRIPTSFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}/helpers/fontmgr/array)"
  local LIST="$(cat ${SCRIPTSFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}/helpers/fontmgr/list)"

  _init_completion || return

  case $prev in
  help | h | --h*)
    return
    ;;
  install | update | remove)
    COMPREPLY=($(compgen -W '${LIST}' -- "$cur"))
    return
    ;;
    
  *)
    COMPREPLY=($(compgen -W '$LIST' -- "$cur"))
    ;;

  esac

    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))

} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # enable completions
  complete -F _fontmgr_completions -o default fontmgr

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
