#!/usr/bin/env bash
# _gen-script_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for gen-script

_gen-script_completions() {
  if [ -d "$HOME/.config/gen-script/files" ]; then
    local GEN_SCRIPTS_TEMPLATE_DIR="$HOME/.config/gen-script/files"
  else
    local GEN_SCRIPTS_TEMPLATE_DIR="/usr/local/share/CasjaysDev/scripts/templates/scripts"
  fi
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local OS=$(ls $GEN_SCRIPTS_TEMPLATE_DIR/os/ 2>/dev/null)
  local SHELL=$(ls $GEN_SCRIPTS_TEMPLATE_DIR/shell/ 2>/dev/null)
  local INSTALLERS=$(ls $GEN_SCRIPTS_TEMPLATE_DIR/installers/ 2>/dev/null)
  local ARRAY="--help config header $(cd $GEN_SCRIPTS_TEMPLATE_DIR/ && ls -d * 2>/dev/null)"

  _init_completion || return

  case $prev in

  installers)
    COMPREPLY=($(compgen -W '$INSTALLERS' -- "$cur"))
    return 0
    ;;

  shell)
    COMPREPLY=($(compgen -W '$SHELL' -- "$cur"))
    return 0
    ;;

  os)
    COMPREPLY=($(compgen -W '$OS' -- "$cur"))
    return 0
    ;;

  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return 0
    ;;
  esac

} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # enable completions
  complete -F _gen-script_completions -o default gen-script

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
