#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : gen-readme --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : gen-readme
# @Description   : autocomplete for gen-readme
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_gen-readme() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local readmeDir="${GEN_README_DIR:-$HOME/.config/gen-readme/files}"
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="all $(<$CASJAYSDEVDIR/helpers/gen-readme/array)"
  local INST="$(find $readmeDir/installers -type f 2>/dev/null | sed 's#'$readmeDir/installers/'##g' 2>/dev/null || return)"
  local PROJ="$(find $readmeDir/projects -type f 2>/dev/null | sed 's#'$readmeDir/projects/'##g' 2>/dev/null || return)"
  local ALL="$(find $readmeDir/ -type f -not -path "$readmeDir/.git/*" | sed 's#'$readmeDir/'##g' | sort -u || return)"

  _init_completion || return

  case $prev in
  project*)
    COMPREPLY=($(compgen -W '$PROJ' -- "$cur"))
    return
    ;;

  install*)
    COMPREPLY=($(compgen -W '$INST' -- "$cur"))
    return
    ;;

  *all)
    COMPREPLY=($(compgen -W '$ALL' -- "$cur"))
    return
    ;;
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gen-readme -o default gen-readme
