#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : gen-license --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : gen-license
# @Description   : autocomplete for gen-license
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_gen-license() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local licenseDir="${GEN_LICENSE_DIR:-$HOME/.config/gen-license/custom}"
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local options="--help --version --config --list --download --custom"
  local ARRAY="$(<$CASJAYSDEVDIR/helpers/gen-license/array)"
  local custom="$(find $licenseDir/ -type f -not -path "$licenseDir/.git/*" | sed 's#'$licenseDir/'##g' | sort -u || return)"

  _init_completion || return
case $prev in
custom)
  COMPREPLY=($(compgen -W '$custom' -- "$cur"))
  ;;
-*)
  COMPREPLY=($(compgen -W '$options' -- "$cur"))
  ;;
*)
  COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
  return
  ;;
esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gen-license -o default gen-license
