#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : gen-script --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : gen-script
# @Description   : autocomplete for gen-script
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_gen-script() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  if [ -d "$HOME/.config/gen-script/files" ]; then
    local GEN_SCRIPTS_TEMPLATE_DIR="$HOME/.config/gen-script/files"
  else
    local GEN_SCRIPTS_TEMPLATE_DIR="$CASJAYSDEVDIR/templates/scripts"
  fi
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local OS=$(ls -A $GEN_SCRIPTS_TEMPLATE_DIR/os/ 2>/dev/null)
  local SHELL=$(ls -A $GEN_SCRIPTS_TEMPLATE_DIR/shell/ 2>/dev/null)
  local BASH=$(ls -A $GEN_SCRIPTS_TEMPLATE_DIR/bash/ 2>/dev/null)
  local INSTALLERS=$(ls -A $GEN_SCRIPTS_TEMPLATE_DIR/installers/ 2>/dev/null)
  local ALL="$(find $GEN_SCRIPTS_TEMPLATE_DIR -type f | sed 's#'$GEN_SCRIPTS_TEMPLATE_DIR/'##g' 2>/dev/null)"
  local ARRAY="--help config header all os shell installers"

  _init_completion || return

  case $prev in
  all)
    shift 1
    COMPREPLY=($(compgen -W '$ALL' -- "$cur"))
    return
    ;;

  installers)
    shift 1
    COMPREPLY=($(compgen -W '$INSTALLERS' -- "$cur"))
    return 0
    ;;

  bash)
    shift 1
    COMPREPLY=($(compgen -W '$BASH' -- "$cur"))
    return 0
    ;;

  shell)
    shift 1
    COMPREPLY=($(compgen -W '$SHELL' -- "$cur"))
    return 0
    ;;

  os)
    shift 1
    COMPREPLY=($(compgen -W '$OS' -- "$cur"))
    return 0
    ;;

  header)
    shift 1
    COMPREPLY=($(compgen -W '--help -t -d -c -o -r -f -i -u --raw' -- "$cur"))
    return 0
    ;;

  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return 0
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gen-script -o default gen-script
