#!/usr/bin/env bash
# _gen-license_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for gen-license

_gen-license_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="$(cat ${SCRIPTSFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}/helpers/gen-license/array)"

  _init_completion || return

  COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# enable completions
complete -F _gen-license_completions -o default gen-license

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
