#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : gen-script --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : gen-script
# @Description   : autocomplete for gen-script
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_gen-script() {
  if [ -d "$HOME/.config/gen-script/files" ]; then
    local GEN_SCRIPTS_TEMPLATE_DIR="$HOME/.config/gen-script/files"
  else
    local GEN_SCRIPTS_TEMPLATE_DIR="/usr/local/share/CasjaysDev/scripts/templates/scripts"
  fi
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local OS=$(ls -A $GEN_SCRIPTS_TEMPLATE_DIR/os/ 2>/dev/null)
  local SHELL=$(ls -A $GEN_SCRIPTS_TEMPLATE_DIR/shell/ 2>/dev/null)
  local INSTALLERS=$(ls -A $GEN_SCRIPTS_TEMPLATE_DIR/installers/ 2>/dev/null)
  local ARRAY="--help config header $(ls -d $GEN_SCRIPTS_TEMPLATE_DIR/* | sed 's#'$GEN_SCRIPTS_TEMPLATE_DIR/'##g' 2>/dev/null)"

  _init_completion || return

  case $prev in

  installers)
    COMPREPLY=($(compgen -W '$INSTALLERS' -- "$cur"))
    return 0
    ;;

  shell)
    COMPREPLY=($(compgen -W '$SHELL' -- "$cur"))
    return 0
    ;;

  os)
    COMPREPLY=($(compgen -W '$OS' -- "$cur"))
    return 0
    ;;

  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return 0
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gen-script -o default gen-script
