#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : gitadmin --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : gitadmin
# @Description   : autocomplete for gitadmin
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_gitadmin() {
  mkdir -p "$HOME/Projects" >/dev/null 2>&1
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="$(<$CASJAYSDEVDIR/helpers/gitadmin/array)"
  local LIST="$(<$CASJAYSDEVDIR/helpers/gitadmin/list)"
  local gitOPTS="init clone remote"
  local automatedOpts="--automated"
  local updateOpts="--while"

  _init_completion || return

  case $prev in
  help | h | --h*)
    return
    ;;
  update)
    COMPREPLY=($(compgen -W '${updateOpts}' -- "$cur"))
    return 0
    ;;

  push)
    k=0
    i="$HOME/Projects"
    if [ "$(find $i/* -maxdepth 1 -type d 2>/dev/null | wc -l)" -ne 0 ]; then
      for d in $(find $i//*/*/* -maxdepth 0 -type d 2>/dev/null); do
      for j in $(compgen -f "$d/$cur"); do
        [ -d "$j" ] && j="${j}"
        COMPREPLY[k++]=${j}
      done
    done
    else
      _filedir
    fi
    return 0
    ;;

  pull)
    k=0
    i="$HOME/Projects"
    if [ "$(find $i/* -maxdepth 1 -type d 2>/dev/null | wc -l)" -ne 0 ]; then
      for d in $(find $i//*/*/* -maxdepth 0 -type d 2>/dev/null); do
        for j in $(compgen -f "$d/$cur"); do
        [ -d "$j" ] && j="${j} "
        COMPREPLY[k++]=${j}
      done
    done
  else
    _filedir
    fi
    return 0
    ;;

  clone)
    COMPREPLY=($(compgen -W '--bare --progress --quiet --recursive --recurse-submodules' -- "$cur"))
    return 1
    ;;

  --org)
    k=0
    i="$HOME/Projects"
    if [ "$(find $i/* -maxdepth 1 -type d 2>/dev/null | wc -l)" -ne 0 ]; then
      for d in $(find $i//*/*/* -maxdepth 0 -type d 2>/dev/null); do
      for j in $(compgen -f "$d/$cur"); do
        [ -d "$j" ] && j="${j}"
        COMPREPLY[k++]=${j#$d/}
      done
    done
  else
    _filedir
    fi
    return 0
    ;;

  github)
    COMPREPLY=($(compgen -W '${gitOPTS}' -- "$cur"))
    return 0
    ;;

  gitlab)
    COMPREPLY=($(compgen -W '${gitOPTS}' -- "$cur"))
    return 0
    ;;

  private)
    COMPREPLY=($(compgen -W '${gitOPTS}' -- "$cur"))
    return 0
    ;;

  setup)
    COMPREPLY=($(compgen -W '${automatedOpts}' -- "$cur"))
    return 0
    ;;

  esac

  COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gitadmin gitadmin
