#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : gitcommit --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : gitcommit
# @Description   : autocomplete for gitcommit
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_gitcommit() {
  local cur prev words cword
  local ARRAY="$(</usr/local/share/CasjaysDev/scripts/helpers/gitcommit/array)"
  local LIST="$(</usr/local/share/CasjaysDev/scripts/helpers/gitcommit/list)"
  _init_completion || return

  if [[ $cur == -* ]]; then
    COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
    return
  fi

  case $prev in
  new)
    _filedir
    return
    ;;

  improve)
    _filedir
    return
    ;;

  fix)
    _filedir
    return
    ;;

  release)
    _filedir
    return
    ;;

  docs)
    _filedir
    return
    ;;

  test)
    _filedir
    return
    ;;

  breaking)
    _filedir
    return
    ;;

  esac

  COMPREPLY=($(compgen -W '${LIST}' -- "$cur"))
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gitcommit -o default gitcommit
