#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : gitignore --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : gitignore
# @Description   : autocomplete for gitignore
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_gitignore() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="$(</usr/local/share/CasjaysDev/scripts/helpers/gitignore/array)"

  _init_completion || return

  case $prev in
  help | h | --h*)
    return
    ;;

  esac

  COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gitignore -o default gitignore
