#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : logr --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : logr
# @Description   : autocomplete for logr
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_logr() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local logdir=${LOG_DIR:-$HOME/.local/log}
  local cur prev words cword
  local cur_word="${COMP_WORDS[$COMP_CWORD]}"
  local ARRAY="--help --list --open --clean --show --noerr --err --silent "
  local OPEN="$(find "$logdir" -type f 2>/dev/null || return)"
  _init_completion || return

  case $prev in
  --open)
    COMPREPLY=($(compgen -W '${OPEN}' -- "$cur"))
    return 0
    ;;

  *)
    if [[ "${cur_word}" == -* ]]; then
      COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
      return 0
    else
      COMPREPLY=($(compgen -c -- "${cur}"))
      return 0
    fi
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _logr -o default logr
