#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : music --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : music
# @Description   : autocomplete for music
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_music() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="$(</usr/local/share/CasjaysDev/scripts/helpers/music/array)"
  local LIST="$(</usr/local/share/CasjaysDev/scripts/helpers/music/list)"

  _init_completion || return

  case $prev in
  help | h | --h*)
    return
    ;;

  *)
    if [[ "${cur}" == -* ]]; then
      COMPREPLY=($(compgen -W '--help' -- "$cur"))
      return 0
    else
      COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      return 0
    fi
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _music -o default music
