#!/usr/bin/env bash
# _mybrowser_completions completion
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# mybrowser for mybrowser

_mybrowser_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="--version --help --config --link http"

  _init_completion || return

  case $prev in
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return 0
    ;;
  esac
} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _mybrowser_completions -o default mybrowser

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
