#!/usr/bin/env bash
# _mydate_completions completion
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# mydate for mydate

_mydate_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="--version --help config nowtime nowdate setver setverfile custom"

  _init_completion || return

  case $prev in
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return 0
    ;;
  esac
} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _mydate_completions -o default mydate

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
