#!/usr/bin/env bash
# _myemail_completions completion
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# myemail for myemail

_myemail_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="--version --help --config --link"

  _init_completion || return

  case $prev in
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return 0
    ;;
  esac
} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _myemail_completions -o default myemail

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
