#!/usr/bin/env bash
# _myeditor_completions completion
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# myeditor for myeditor

_myeditor_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="--version --help --config --link ."

  _init_completion || return

  case $prev in
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return 0
    ;;
  esac
} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _myeditor_completions -o default myeditor

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
