#!/usr/bin/env bash
# _myfilemanager_completions completion
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# myfilemanager for myfilemanager

_myfilemanager_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="--version --help --config --link ."

  _init_completion || return

  case $prev in
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return 0
    ;;
  esac
} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _myfilemanager_completions -o default myfilemanager

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
