#!/usr/bin/env bash
# _myshell_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for myshell

_myshell_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY=$(for line in $(cat /etc/shells | grep -v "#"); do basename "$line" | tr '\n' ' '; done && echo)

  _init_completion || return
  case $prev in
  *)
    COMPREPLY=($(compgen -W '--help ${ARRAY}' -- "$cur"))
    return
    ;;
  esac
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# enable completions
complete -F _myshell_completions -o default myshell

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
