#!/usr/bin/env bash
# _myvmmanager_completions completion
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# myvmmanager for myvmmanager

_myvmmanager_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="--version --help --config --link"

  _init_completion || return

  case $prev in
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return 0
    ;;
  esac
} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _myvmmanager_completions -o default myvmmanager

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
