#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : node --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : node
# @Description   : autocomplete for node
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_node() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur_word options
  local cur_word="${COMP_WORDS[$COMP_CWORD]}"
  local options+="--max-http-header-size --experimental-specifier-resolution --inspect-brk-node "
  local options+=" --heap-prof-name --insecure-http-parser --inspect-brk --heap-prof --expose-internals "
  local options+="--prof-process --experimental-import-meta-resolve --trace-deprecation --no-force-async-hooks-checks "
  local options+="--heapsnapshot-signal --cpu-prof --cpu-prof-interval --experimental-report --heap-prof-dir --test-udp-no-try-send "
  local options+="--tls-max-v1.2 --inspect-port --tls-min-v1.1 --pending-deprecation --experimental-wasm-modules --tls-keylog --print "
  local options+="--eval --openssl-config --trace-uncaught --force-context-aware --debug --tls-min-v1.2 --report-uncaught-exception "
  local options+="--experimental-wasi-unstable-preview1 --cpu-prof-dir --interactive --trace-sigint --zero-fill-buffers --tls-max-v1.3 "
  local options+="--check --experimental-json-modules --tls-cipher-list --trace-event-file-pattern --debug-brk --cpu-prof-name --inspect "
  local options+="--help --use-largepages --report-on-fatalerror --tls-min-v1.3 --version --perf-prof-unwinding-info --v8-pool-size "
  local options+="--completion-bash --abort-on-uncaught-exception --no-deprecation --jitless --use-openssl-ca --security-revert "
  local options+="--inspect-publish-uid --unhandled-rejections --icu-data-dir --napi-modules --v8-options --use-bundled-ca --throw-deprecation "
  local options+=" --report-directory --perf-basic-prof --debug-arraybuffer-allocations --disallow-code-generation-from-strings --report-on-signal "
  local options+="--experimental-vm-modules --preserve-symlinks-main --max-old-space-size --require --report-signal --input-type --trace-warnings "
  local options+="--report-filename --title --es-module-specifier-resolution --interpreted-frames-native-stack --no-warnings "
  local options+="--perf-basic-prof-only-functions --no-node-snapshot --experimental-policy --perf-prof --stack-trace-limit "
  local options+="--http-parser --experimental-repl-await --frozen-intrinsics --track-heap-objects --trace-event-categories "
  local options+="--tls-min-v1.0 --experimental-loader --trace-exit --redirect-warnings --trace-tls --heap-prof-interval --preserve-symlinks "
  local options+="--policy-integrity --enable-source-maps --experimental-worker --trace-sync-io --experimental-modules --inspect-brk= --debug-port "
  local options+="--debug= -i --inspect= --prof-process -pe -p --loader -c --debug-brk= -e --print <arg> -r --security-reverts "
  local options+="--inspect-brk-node= -h --trace-events-enabled -v"
  if [[ "${cur_word}" == -* ]]; then
    COMPREPLY=($(compgen -W '$options' -- "${cur_word}"))
    return 0
  else
    COMPREPLY=($(compgen -f "${cur_word}"))
    return 0
  fi
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _node node node_g
