#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : notes --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : notes
# @Description   : autocomplete for notes
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_notes() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local notesdir="${NOTES_DIRECTORY:-$HOME/.local/share/editors/notes}"
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="client --help all --show --config --server open sync list search --import"
  local SERVEROPTS="--help --kill --status systemd edit enable start"
  local SYSTEMD="install remove start stop restart status run"
  local SYSTEMDRUN="vars stop start restart"
  local OPEN="$(find $notesdir/*/* -type f -iname "*.txt" -o -iname "*.md" -not -path "$notesdir/.git/*" -not -path "$notesdir/archive/*" 2>/dev/null | sed 's#'$notesdir/'##g')"
  local EDIT="all prev cur"

  _init_completion || return

  case "$prev" in
  *server | *service)
    COMPREPLY=($(compgen -W '$SERVEROPTS' -- "$cur"))
    return
    ;;

  *systemd)
    COMPREPLY=($(compgen -W '$SYSTEMD' -- "$cur"))
    return
    ;;

  *run)
    COMPREPLY=($(compgen -W '$SYSTEMDRUN' -- "$cur"))
    return
    ;;

  *client)
    COMPREPLY=($(compgen -W '$(_filedir)' -- "$cur"))
    return
    ;;

  *edit)
    COMPREPLY=($(compgen -W '${EDIT}' -- "$cur"))
    return
    ;;

  *open)
    COMPREPLY=($(compgen -W 'all $OPEN' -- "$cur"))
    return
    ;;

  -)
    COMPREPLY=($(compgen -W '--help --version' -- "$cur"))
    return
    ;;

  *)
    COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
    return
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _notes notes
