#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : notifications --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : notifications
# @Description   : autocomplete for notifications
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_notifications() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="--help --bg --all config client"
  _init_completion || return

  case $prev in
  --all)
    _allowed_users
    ;;
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return 0
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _notifications -o default notifications
