#!/usr/bin/env bash
# _notes_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for notes

_notes_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="- --help --status --all config client open server"
  local SERVEROPTS="--kill systemd open enable start"
  local SYSTEMD="install remove start stop restart status run"
  local SYSTEMDRUN="vars stop start restart"

  _init_completion || return

  case "$prev" in
  --*)
    return 1
    ;;

  *server | *service)
    COMPREPLY=($(compgen -W '${SERVEROPTS}' -- "$cur"))
    return
    ;;

  *systemd)
    COMPREPLY=($(compgen -W '$SYSTEMD' -- "$cur"))
    return
    ;;

  *run)
    COMPREPLY=($(compgen -W '$SYSTEMDRUN' -- "$cur"))
    return
    ;;

  *client)
    _filedir
    return
    ;;

  *open)
    COMPREPLY=($(compgen -W 'all' -- "$cur"))
    return
    ;;

  *)
    COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
    return
    ;;
  esac

} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # enable completions
  complete -F _notes_completions -o default notes

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
