#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : pkmgr --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : pkmgr
# @Description   : autocomplete for pkmgr
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_pkmgr() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="$(</usr/local/share/CasjaysDev/scripts/helpers/pkmgr/array)"
  local dotfiles="$(</usr/local/share/CasjaysDev/scripts/helpers/dotfiles/list)"
  _init_completion || return

  case $prev in
  help | h | --h*)
    return
    ;;

  dotfiles)
    COMPREPLY=($(compgen -W '${dotfiles}' -- "$cur"))
    return
    ;;

  script)
    COMPREPLY=($(compgen -W '--verbose --script' -- "$cur"))
    return
    ;;

  *)
    COMPREPLY=($(compgen -W '$LIST' -- "$cur"))
    ;;

  esac

  COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _pkmgr -o default pkmgr
