#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : randomwallpaper --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : randomwallpaper
# @Description   : autocomplete for randomwallpaper
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_randomwallpaper() {
  local cur prev words cword
  local ARRAY="--bg --help --term config startup ."

  _init_completion || return

  case $prev in
  -*)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return
    ;;

  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _randomwallpaper -o default randomwallpaper
