#!/usr/bin/env bash
# _run_in_term_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for run_in_term

_run_in_term_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"

  _init_completion || return

  case $prev in
  *)
    COMPREPLY=( $(compgen -c -- "${cur}") )
    return 0
    ;;
  esac

} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # enable completions
  complete -F _run_in_term_completions -o default run_in_term

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
