#!/usr/bin/env bash
# _run_command_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for run_command

_run_command_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"

  _init_completion || return

  case $prev in
  *)
    COMPREPLY=( $(compgen -c -- "${cur}") )
    return 0
    ;;
  esac

} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # enable completions
  complete -F _run_command_completions -o default run_command

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
