#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : scratchpad --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : scratchpad
# @Description   : autocomplete for scratchpad
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_scratchpad() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local scratchdir="${SCRATCHAD_DIR:-$HOME/.local/share/editors/scratchpads}"
  local ARRAY="$(</usr/local/share/CasjaysDev/scripts/helpers/scratchpad/array)"
  local OPEN="$(find $scratchdir/*/* -type f | sed 's#'$scratchdir/'##g')"
  _init_completion || return

  case $prev in
  open)
    COMPREPLY=($(compgen -W '$OPEN' -- "$cur"))
    ;;

  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    ;;
  esac

} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _scratchpad -o default scratchpad
