#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : scratchpad --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : scratchpad
# @Description   : autocomplete for scratchpad
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_scratchpad() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local scratchDir="${SCRATCHAD_DIR:-$HOME/.local/share/editors/scratchpads}"
  local cur prev words cword
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local ARRAY="$(<$CASJAYSDEVDIR/helpers/scratchpad/array)"
  local OPEN="$(find $scratchDir/*/* -not -path "$scratchDir/.git/*" -type f 2>/dev/null | sed 's#'$scratchDir/'##g' || return)"

  _init_completion || return

  case $prev in
  remove)
    COMPREPLY=($(compgen -W '$OPEN' -- "$cur"))
    return
    ;;
  open)
    COMPREPLY=($(compgen -W '$OPEN' -- "$cur"))
    return
    ;;
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    return
    ;;
  esac

} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _scratchpad scratchpad
