#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : sudoers --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : sudoers
# @Description   : autocomplete for sudoers
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_sudoers() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="$(<$CASJAYSDEVDIR/helpers/sudoers/array)"

  _init_completion || return

  case $prev in
  help | h | --h*)
    return
    ;;

  adduser | remuser)
    COMPREPLY=($(compgen -u -- "$cur"))
    ;;

  esac

  COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _sudoers -o default sudoer &&
  complete -F _sudoers -o default sudoers
