#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202103290512-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : sudoers --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Monday, Mar 29, 2021 08:43 EDT
# @File          : sudoers
# @Description   : add and remove users from sudo
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#_sudoers --options &>/dev/null
_sudoers() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/myscripts/sudoers"
  local OPTSDIR="$HOME/.local/share/myscripts/sudoers/options"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/sudoers}"
  #local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1")"
  local DEFAULTARRAY="$([ -f "$OPTSDIR/array" ] && grep -sEv '#|^$' "$OPTSDIR/array")"
  local DEFAULTOPTS="$([ -f "$OPTSDIR/options" ] && grep -sEv '#|^$' "$OPTSDIR/options" || echo -v -h)"
  local LONGOPTS="$(grep -sEv '#|^$' "$OPTSDIR/long_opts" || echo "$DEFAULTOPTS" | tr ' ' '\n' | grep '\--')"
  local SHORTOPTS="$(grep -sEv '#|^$' "$OPTSDIR/short_opts" || echo "$DEFAULTOPTS" | tr ' ' '\n' | grep -v '\--')"
  local OPTS="$DEFAULTOPTS"
  local ARRAY="remove remuser adduser pass nopass insults status command"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""

  _init_completion || return
  if [ "$SHOW_COMP_OPTS" != "" ]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi
  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
  else
    case ${COMP_WORDS[1]:-$prev} in
    --options) prev="--options" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    -c | --config) prev="--config" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    -h | --help) prev="--help" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    -v | --version) prev="--version" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    remove) prev="remove" && COMPREPLY=($(compgen -u -- "$cur")) ;;
    remuser) prev="remuser" && COMPREPLY=($(compgen -u -- "$cur")) ;;
    adduser) prev="adduser" && COMPREPLY=($(compgen -u -- "$cur")) ;;
    pass) prev="pass" && COMPREPLY=($(compgen -u -- "$cur")) ;;
    nopass) prev="nopass" && COMPREPLY=($(compgen -u -- "$cur")) ;;
    insults) prev="insults" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    status) prev="status" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    command) shift 1 && prev="${COMP_WORDS[0]}" && COMPREPLY=($(compgen -c -- "${cur}")) ;;
    -) prev="-" && COMPREPLY=($(compgen -W '${SHORTOPTS} ${LONGOPTS}' -- ${cur})) ;;
    *)
      COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      #if [ -n "$FILEDIR" ]; then _filedir; fi
      #if [[ "$ARRAY" = "show-none" ]]; then
      #  COMPREPLY=($(compgen -W '' -- "${cur}"))
      #elif [[ "$ARRAY" = "show-_filedir" ]]; then
      #  _filedir
      #elif [[ "$ARRAY" = "show-commands" ]]; then
      #  COMPREPLY=($(compgen -c -- "${cur}"))
      #elif [[ -n "$ARRAY" ]]; then
      #[ $COMP_CWORD -eq 3 ] && \
      #  COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      #elif [[ -n "$OPTS" ]]; then
      #[ $COMP_CWORD -gt 3 ] && \
      #  COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      #fi
      return
      ;;
    esac
    $split && return
  fi
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _sudoers sudoers
