#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : scratchpad --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : scratchpad
# @Description   : autocomplete for scratchpad
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_tasks() {
  local cur prev words cword
  local ARRAY="list add report cleanup info done session switch stop start delete "

  _init_completion || return

  # relevant options completion
  COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))

} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _tasks -o default tasks
