#!/usr/bin/env bash
# _todo_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for todo

_todo_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="$(cat ${SCRIPTSFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}/helpers/todo/array)"

  _init_completion || return

  case $prev in
  list)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    ;;

  open)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    ;;

  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    ;;
  esac

} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # enable completions
  complete -F _todo_completions -o default todo

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
