#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : trash --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : trash
# @Description   : autocomplete for trash
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_trash() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword
  local prefix=trash
  local trashdir="${TRASH_DIR:-$HOME/.local/share/Trash/files}"
  local trashlist="$(find -L $trashdir/* 2>/dev/null)"
  local LIST="${trashlist//$trashdir\/}"
  local ARRAY="--help --version list restore remove empty"

  local cur prev words cword split
  _init_completion -s || return

  list_all() {
    COMPREPLY=($(compgen -W '${LIST}' -- "$cur"))
  }

  local special i
  for ((i = 1; i < ${#words[@]} - 1; i++)); do
    if [[ ${words[i]} == @(list|restore|ls|rs) ]]; then
      special=${words[i]}
      break
    fi
  done

  if [[ -v special ]]; then
    if [[ $cur == @(*/|[.~])* && \
      $special == @(list|restore|ls|rs) ]]; then
      list_all
      return
    fi

    case $special in
    list | restore | ls | rs)
      list_all
      return
      ;;
    esac
  fi

  case $prev in
  remove | rm)
    _filedir
    return
    ;;
  empty)
    return 0
    ;;
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    ;;
  esac

  $split && return

} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _trash -o default trash
