#!/usr/bin/env bash
# _trash_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for trash

_trash_completions() {
  local cur prev words cword
  local prefix=trash
  local ARRAY="--help list restore remove empty"
  local LIST="$(list ${TRASH_DIR:-$HOME/.local/share/Trash/files/})"

  local cur prev words cword split
  _init_completion -s || return

  list_all() {
    COMPREPLY=($(compgen -W '${LIST}' -- "$cur"))
  }

  local special i
  for ((i = 1; i < ${#words[@]} - 1; i++)); do
    if [[ ${words[i]} == @(list|restore|ls|rs) ]]; then
      special=${words[i]}
      break
    fi
  done

  if [[ -v special ]]; then
    if [[ $cur == @(*/|[.~])* && \
      $special == @(list|restore|ls|rs) ]]; then
      list_all
      return
    fi

    case $special in
    list | restore | ls | rs)
      list_all
      return
      ;;
    esac
  fi

  case $prev in
  remove | rm)
    _filedir
    return
    ;;
  empty)
    return 0
    ;;
  *)
    COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))
    ;;
  esac

  $split && return

} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # enable completions
  complete -F _trash_completions -o default trash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
