#!/usr/bin/env bash
# _wallpapermgr_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for wallpapermgr

_wallpapermgr_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="$(cat ${SCRIPTSFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}/helpers/wallpapermgr/array)"
  local LIST="$(cat ${SCRIPTSFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}/helpers/wallpapermgr/list)"

  _init_completion || return

  case $prev in
  help | h | --h*)
    return
    ;;

  install | update | remove)
    COMPREPLY=($(compgen -W '${LIST}' -- "$cur"))
    ;;

  *)
    COMPREPLY=($(compgen -W '$LIST' -- "$cur"))
    ;;

  esac

  COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))

} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # enable completions
  complete -F _wallpapermgr_completions -o default wallpapermgr

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
