#!/usr/bin/env bash
# _weather_completions completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# autocomplete for weather

_weather_completions() {
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local ARRAY="help city v2 img moon"

  _init_completion || return

  case $prev in
  help | h | --h*)
    return
    ;;

  esac

  COMPREPLY=($(compgen -W '$ARRAY' -- "$cur"))

} &&

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # enable completions
  complete -F _weather_completions -o default weather
